### ISSUE TITLE
MongoDB no longer starts on Windows by default

### ISSUE THREAD

**Issue by MarekSuchanek** [ankane/setup-mongodb#1]
As runner images changed for Windows (MongoDB is stopped+disabled by default), the action no longer works there: https://github.com/ankane/setup-mongodb/blob/v1/index.js#L35

See: https://github.com/actions/runner-images/issues/5949

For now, I overcome the issue by adding this step before `setup-mongodb` (based on suggestion in the runner-images issue):

```yaml
      - name: Start MongoDB (Win service)
        if: matrix.os == 'windows-latest'
        run: |
          Set-Service mongodb -StartupType Automatic          
          Start-Service -Name mongodb
```
